### ISSUE TITLE
Error at startup 

### ISSUE THREAD

**Issue by spearway** [bluemaex/homebridge-dmxuniverse#1]
There is a very curious error during startup:

[7/4/2017, 8:30:12 AM] ====================
[7/4/2017, 8:30:12 AM] ERROR LOADING PLUGIN homebridge-dmxuniverse:
[7/4/2017, 8:30:12 AM] Error: Cannot find module 'hap-nodejs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-dmxuniverse/devices/eurolite-led-bar.js:1:79)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
[7/4/2017, 8:30:12 AM] ====================

**Comment by spearway** [comment]
hap-nodejs is missing in  the dependencies

**Comment by Joebayld** [comment]
Did you find a fix for this?

**Comment by bluemaex** [comment]
@Joebayld @spearway  Sorry for the late reply but I just reinstalled everything yesterday and did not run into this error.  Do you have homebridge installed in the same folder?

Hap-js is indeed a dependency, but as it is already installed via the required homebridge I did not add it again. If you have this package running outside of your homebridge install you need to add it.

I personally have a package.json with which I install homebridge and all its plugins:
```json
{
 "dependencies": {
    "homebridge": "^0.4.22",
    "homebridge-dmxuniverse": "^0.2.3"
  }
}
```

**Comment by bluemaex** [comment]
@Joebayld @spearway I am going to close this issue here, as there hasn't been a response for a while - so I guess this problem is solved? 

If not, please do not hesitate to reopen it and add your questions/problems! Thank you!
