### ISSUE TITLE
Error Loading Plugin

### ISSUE THREAD

**Issue by YannickHaas** [bluemaex/homebridge-dmxuniverse#6]
ERROR LOADING PLUGIN homebridge-dmxuniverse:
[2018-9-5 14:19:24] Error: Cannot find module 'hap-nodejs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-dmxuniverse/devices/eurolite-led-bar.js:1:100)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I can't start the plugin in Homebridge without this error. What can I do?

**Comment by bluemaex** [comment]
Looks like the same error as in issue #1. 

If you install the plugin in a different directory then honmebridge you get this error. Easiest fix is to add hap-nodejs to the dependencies in this package. (aka ``npm install hap-nodejs``)

I shall add that to the next version - Tried to avoid doing that so I do not have a different version of the package than in Homebridge.

**Comment by YannickHaas** [comment]
thank's, that works!
